import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ToastProvider";
import "react-toastify/dist/ReactToastify.css";
const alexandria = Alexandria({ subsets: ["arabic", "latin"] });

export const metadata: Metadata = {
  title: "Enshaa App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={alexandria.className}>
        <ToastProvider>{children}</ToastProvider>
        <div id="modal" />
        <div id="pop-up" />
      </body>
    </html>
  );
}
